name: shabbat city
favicon: null
layout_spectrum: 0.74676
typography_spectrum: 0.95726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3a2a51'
    - '#7f9499'
    - '#ebf3e4'
    - '#a1c6b4'
    - '#5f647a'
  brandStrength: 1
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0
purpose: []
